[dev]
  functions = "netlify/functions"
  publish = "build"

[build]
command = "vite build"
functions = "netlify/functions"
publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200